from pydantic import BaseModel, Field


class TransactionData(BaseModel):
    Time: float = Field(description="Transaction time")
    V1: float = Field(description="Anonymized feature V1")
    V2: float = Field(description="Anonymized feature V2")
    V3: float = Field(description="Anonymized feature V3")
    V4: float = Field(description="Anonymized feature V4")
    V5: float = Field(description="Anonymized feature V5")
    V6: float = Field(description="Anonymized feature V6")
    V7: float = Field(description="Anonymized feature V7")
    V8: float = Field(description="Anonymized feature V8")
    V9: float = Field(description="Anonymized feature V9")
    V10: float = Field(description="Anonymized feature V10")
    V11: float = Field(description="Anonymized feature V11")
    V12: float = Field(description="Anonymized feature V12")
    V13: float = Field(description="Anonymized feature V13")
    V14: float = Field(description="Anonymized feature V14")
    V15: float = Field(description="Anonymized feature V15")
    V16: float = Field(description="Anonymized feature V16")
    V17: float = Field(description="Anonymized feature V17")
    V18: float = Field(description="Anonymized feature V18")
    V19: float = Field(description="Anonymized feature V19")
    V20: float = Field(description="Anonymized feature V20")
    V21: float = Field(description="Anonymized feature V21")
    V22: float = Field(description="Anonymized feature V22")
    V23: float = Field(description="Anonymized feature V23")
    V24: float = Field(description="Anonymized feature V24")
    V25: float = Field(description="Anonymized feature V25")
    V26: float = Field(description="Anonymized feature V26")
    V27: float = Field(description="Anonymized feature V27")
    V28: float = Field(description="Anonymized feature V28")
    Amount: float = Field(description="Transaction amount")